# fly.toml app configuration file generated for server-withered-firefly-7673 on 2024-10-25T14:04:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-withered-firefly-7673'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "8080"